spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: password

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health